# name: Generate snake animation

# on:
#   schedule: # execute every 12 hours
#     - cron: "0 */12 * * *"
  
#   workflow_dispatch:
  
#   push:
#     branches:
#       - main

# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     timeout-minutes: 5

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Create dist directory if not exists
#         run: mkdir -p dist

#       - name: Generate snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           outputs: dist/snake.svg?palette=github-dark

#       - name: Commit and push changes
#         run: |
#           git config --global user.name 'github-actions[bot]'
#           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#           git add dist/snake.svg
#           git commit -m "Generate snake.svg"
#           git push
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }

